export type PhotoCategory =
  | ""
  | "family"
  | "couples"
  | "maternity"
  | "newborn"
  | "children"
  | "portrait"
  | "brand"
  | "atelier"
  | "boudoir"
  | "reportage"
  | "romantic"
  | "wedding";

export interface Photo {
  id: string;
  src: string;
  alt: string;
  title: string;
  category: PhotoCategory;
  size: "small" | "medium" | "large";
}

export const categoryLabels: Record<PhotoCategory, string> = {
  "": "Vše",
  family: "Rodinné",
  couples: "Párové",
  maternity: "Těhotenské",
  newborn: "Newborn",
  children: "Děti",
  portrait: "Portrétní",
  brand: "Brandové",
  atelier: "Ateliérové",
  boudoir: "Boudoir",
  reportage: "Reportážní",
  romantic: "Romantické",
  wedding: "Svatební",
};

export const getAvailableCategories = (photoList: Photo[]) => {
  const unique = new Set<PhotoCategory>();
  unique.add("" as PhotoCategory); // Always include "All"
  photoList.forEach((photo) => {
    if (photo.category) unique.add(photo.category);
  });
  return Array.from(unique).map((cat) => ({
    value: cat,
    label: categoryLabels[cat],
  }));
};

export const photos: Photo[] = [
  // ATELIEROVE
  {
    id: "atelier-1",
    src: "/photos/atelierove/Atelierove foceni. Cesky raj.jpg",
    alt: "Ateliérové focení v Českém ráji",
    title: "Ateliér – Český ráj",
    category: "atelier",
    size: "large",
  },
  {
    id: "atelier-2",
    src: "/photos/atelierove/Atelierove foceni.brandove.foceni.1.jpg",
    alt: "Ateliérové brandové focení",
    title: "Ateliér – Brandové focení",
    category: "atelier",
    size: "medium",
  },
  {
    id: "atelier-3",
    src: "/photos/atelierove/Atelierove foceni.brandove.foceni.jpg",
    alt: "Ateliérové brandové focení",
    title: "Ateliér – Brandové focení 2",
    category: "atelier",
    size: "small",
  },
  {
    id: "atelier-4",
    src: "/photos/atelierove/Atelierove foceni.Cesky raj.jpg",
    alt: "Ateliérové focení Český ráj",
    title: "Ateliér – Český ráj 2",
    category: "atelier",
    size: "medium",
  },
  {
    id: "atelier-5",
    src: "/photos/atelierove/Atelierove foceni.Narozeninove foceni 2.jpg",
    alt: "Narozeninové focení v ateliéru",
    title: "Ateliér – Narozeniny",
    category: "atelier",
    size: "large",
  },
  {
    id: "atelier-6",
    src: "/photos/atelierove/Atelierove foceni.Narozeninove foceni.jpg",
    alt: "Narozeninové focení v ateliéru",
    title: "Ateliér – Narozeniny 2",
    category: "atelier",
    size: "small",
  },
  {
    id: "atelier-7",
    src: "/photos/atelierove/Atelierove foceni.portretni.foceni.2.jpg",
    alt: "Portrétní focení v ateliéru",
    title: "Ateliér – Portrét",
    category: "atelier",
    size: "medium",
  },
  {
    id: "atelier-8",
    src: "/photos/atelierove/Atelierove foceni.portretni.foceni.3.jpg",
    alt: "Portrétní focení v ateliéru",
    title: "Ateliér – Portrét 2",
    category: "atelier",
    size: "large",
  },
  {
    id: "atelier-9",
    src: "/photos/atelierove/Atelierove foceni.portretni.foceni.4.jpg",
    alt: "Portrétní focení v ateliéru",
    title: "Ateliér – Portrét 3",
    category: "atelier",
    size: "small",
  },
  {
    id: "atelier-10",
    src: "/photos/atelierove/Atelierove foceni.portretni.foceni.jpg",
    alt: "Portrétní focení v ateliéru",
    title: "Ateliér – Portrét 4",
    category: "atelier",
    size: "medium",
  },
  {
    id: "atelier-11",
    src: "/photos/atelierove/Atelierove foceni.Tehotenske. Cesky raj.jpg",
    alt: "Těhotenské focení v ateliéru, Český ráj",
    title: "Ateliér – Těhotenství",
    category: "atelier",
    size: "large",
  },
  {
    id: "atelier-12",
    src: "/photos/atelierove/Atelierove foceni.tehotenske.foceni 1.jpg",
    alt: "Těhotenské focení v ateliéru",
    title: "Ateliér – Těhotenství 2",
    category: "atelier",
    size: "small",
  },
  {
    id: "atelier-13",
    src: "/photos/atelierove/Atelierove foceni.tehotenske.foceni.jpg",
    alt: "Těhotenské focení v ateliéru",
    title: "Ateliér – Těhotenství 3",
    category: "atelier",
    size: "medium",
  },

  // BOUDOIR
  {
    id: "boudoir-1",
    src: "/photos/boudoir/Boudoir foceni.Branzez .1.jpg",
    alt: "Boudoir focení Bránžež",
    title: "Boudoir – Bránžež",
    category: "boudoir",
    size: "large",
  },
  {
    id: "boudoir-2",
    src: "/photos/boudoir/Boudoir foceni.Branzez.jpg",
    alt: "Boudoir focení Bránžež",
    title: "Boudoir – Bránžež 2",
    category: "boudoir",
    size: "medium",
  },

  // BRANDOVE
  {
    id: "brand-1",
    src: "/photos/brandove/Brandove foceni.2.jpg",
    alt: "Brandové focení",
    title: "Brandové focení",
    category: "brand",
    size: "large",
  },
  {
    id: "brand-2",
    src: "/photos/brandove/Brandove foceni.Turnov.jpg",
    alt: "Brandové focení Turnov",
    title: "Brandové focení – Turnov",
    category: "brand",
    size: "medium",
  },

  // DETI
  {
    id: "children-1",
    src: "/photos/deti/Foceni deti. Cesky raj. Jicin . Michaela Cizkova.jpg.jpg",
    alt: "Focení dětí Český ráj, Jičín",
    title: "Děti – Český ráj",
    category: "children",
    size: "large",
  },
  {
    id: "children-2",
    src: "/photos/deti/Foceni deti.Sobotka. Cesky raj.jpg",
    alt: "Focení dětí Sobotka, Český ráj",
    title: "Děti – Sobotka",
    category: "children",
    size: "medium",
  },

  // NEWBORN
  {
    id: "newborn-1",
    src: "/photos/newborn/Newborn foceni Cesky raj. 3. Michaela Cizkova.jpg.jpg",
    alt: "Newborn focení Český ráj",
    title: "Novorozenec – Český ráj",
    category: "newborn",
    size: "large",
  },
  {
    id: "newborn-2",
    src: "/photos/newborn/Newborn foceni Cesky raj. 4. Michaela Cizkova.jpg.jpg",
    alt: "Newborn focení Český ráj",
    title: "Novorozenec – Český ráj 2",
    category: "newborn",
    size: "small",
  },
  {
    id: "newborn-3",
    src: "/photos/newborn/Newborn foceni Cesky raj. 5. Michaela Cizkova.jpg",
    alt: "Newborn focení Český ráj",
    title: "Novorozenec – Český ráj 3",
    category: "newborn",
    size: "medium",
  },
  {
    id: "newborn-4",
    src: "/photos/newborn/Newborn foceni Cesky raj. Michaela Cizkova.2.jpg",
    alt: "Newborn focení Český ráj",
    title: "Novorozenec – Český ráj 4",
    category: "newborn",
    size: "large",
  },
  {
    id: "newborn-5",
    src: "/photos/newborn/Newborn foceni. Turnov.jpg",
    alt: "Newborn focení Turnov",
    title: "Novorozenec – Turnov",
    category: "newborn",
    size: "small",
  },
  {
    id: "newborn-6",
    src: "/photos/newborn/Newborn foceni.Mlada Boleslav.jpg",
    alt: "Newborn focení Mladá Boleslav",
    title: "Novorozenec – Mladá Boleslav",
    category: "newborn",
    size: "medium",
  },

  // PAROVE
  {
    id: "couples-1",
    src: "/photos/parove/Parove foceni Cesky raj. Jicin. Michaela Cizkova.jpg.jpg",
    alt: "Párové focení Český ráj, Jičín",
    title: "Párové – Jičín",
    category: "couples",
    size: "large",
  },
  {
    id: "couples-2",
    src: "/photos/parove/Parove foceni Cesky raj. Lovec. Michaela Cizkova.jpg.jpg",
    alt: "Párové focení Český ráj, Lovce",
    title: "Párové – Lovec",
    category: "couples",
    size: "medium",
  },
  {
    id: "couples-3",
    src: "/photos/parove/Parove foceni Cesky raj. Michaela Cizkova.jpg.jpg",
    alt: "Párové focení Český ráj",
    title: "Párové – Český ráj",
    category: "couples",
    size: "small",
  },
  {
    id: "couples-4",
    src: "/photos/parove/Parove foceni Jicin. Michaela Cizkova.1jpg.jpg",
    alt: "Párové focení Jičín",
    title: "Párové – Jičín 2",
    category: "couples",
    size: "large",
  },
  {
    id: "couples-5",
    src: "/photos/parove/Parove foceni Jicin. Michaela Cizkova.jpg",
    alt: "Párové focení Jičín",
    title: "Párové – Jičín 3",
    category: "couples",
    size: "medium",
  },
  {
    id: "couples-6",
    src: "/photos/parove/Parove foceni.Jicin. jpg.jpg",
    alt: "Párové focení Jičín",
    title: "Párové – Jičín 4",
    category: "couples",
    size: "small",
  },
  {
    id: "couples-7",
    src: "/photos/parove/Parove foceni.Na Radouci.1.jpg",
    alt: "Párové focení Na Radouči",
    title: "Párové – Na Radouči",
    category: "couples",
    size: "large",
  },
  {
    id: "couples-8",
    src: "/photos/parove/Parove foceni.Na Radouci.jpg",
    alt: "Párové focení Na Radouči",
    title: "Párové – Na Radouči 2",
    category: "couples",
    size: "medium",
  },
  {
    id: "couples-9",
    src: "/photos/parove/Parove foceni.Pod Zebinem.1.jpg",
    alt: "Párové focení pod Zebínem",
    title: "Párové – Pod Zebínem",
    category: "couples",
    size: "small",
  },
  {
    id: "couples-10",
    src: "/photos/parove/Parove foceni.Pod Zebinem.2.jpg",
    alt: "Párové focení pod Zebínem",
    title: "Párové – Pod Zebínem 2",
    category: "couples",
    size: "large",
  },
  {
    id: "couples-11",
    src: "/photos/parove/Parove foceni.Pod Zebinem.jpg",
    alt: "Párové focení pod Zebínem",
    title: "Párové – Pod Zebínem 3",
    category: "couples",
    size: "medium",
  },
  {
    id: "couples-12",
    src: "/photos/parove/Parove foceni.Trosky.Turnov.1.jpg",
    alt: "Párové focení Trosky, Turnov",
    title: "Párové – Trosky",
    category: "couples",
    size: "small",
  },
  {
    id: "couples-13",
    src: "/photos/parove/Parove foceni.Trosky.Turnov.2.jpg",
    alt: "Párové focení Trosky, Turnov",
    title: "Párové – Trosky 2",
    category: "couples",
    size: "large",
  },
  {
    id: "couples-14",
    src: "/photos/parove/Parove foceni.Trosky.Turnov.3.jpg",
    alt: "Párové focení Trosky, Turnov",
    title: "Párové – Trosky 3",
    category: "couples",
    size: "medium",
  },
  {
    id: "couples-15",
    src: "/photos/parove/Parove foceni.Trosky.Turnov.4.jpg",
    alt: "Párové focení Trosky, Turnov",
    title: "Párové – Trosky 4",
    category: "couples",
    size: "small",
  },
  {
    id: "couples-16",
    src: "/photos/parove/Parove foceni.Trosky.Turnov.jpg",
    alt: "Párové focení Trosky, Turnov",
    title: "Párové – Trosky 5",
    category: "couples",
    size: "large",
  },

  // PORTRETNI
  {
    id: "portrait-1",
    src: "/photos/portretni/Portretni foceni Cesky raj. 2. Michaela Cizkova.jpg.jpg",
    alt: "Portrétní focení Český ráj",
    title: "Portrét – Český ráj",
    category: "portrait",
    size: "large",
  },
  {
    id: "portrait-2",
    src: "/photos/portretni/Portretni foceni Cesky raj. Liberec. Michaela Cizkova.jpg.jpg",
    alt: "Portrétní focení Český ráj, Liberec",
    title: "Portrét – Liberec",
    category: "portrait",
    size: "medium",
  },
  {
    id: "portrait-3",
    src: "/photos/portretni/Portretni foceni v prirode. Cesky raj.2.jpg",
    alt: "Portrétní focení v přírodě, Český ráj",
    title: "Portrét v přírodě – Český ráj",
    category: "portrait",
    size: "small",
  },
  {
    id: "portrait-4",
    src: "/photos/portretni/Portretni foceni v prirode. Cesky raj.3.jpg",
    alt: "Portrétní focení v přírodě, Český ráj",
    title: "Portrét v přírodě – Český ráj 2",
    category: "portrait",
    size: "large",
  },
  {
    id: "portrait-5",
    src: "/photos/portretni/Portretni foceni v prirode. Cesky raj.4.jpg",
    alt: "Portrétní focení v přírodě, Český ráj",
    title: "Portrét v přírodě – Český ráj 3",
    category: "portrait",
    size: "medium",
  },
  {
    id: "portrait-6",
    src: "/photos/portretni/Portretni foceni v prirode. Cesky raj.jpg",
    alt: "Portrétní focení v přírodě, Český ráj",
    title: "Portrét v přírodě – Český ráj 4",
    category: "portrait",
    size: "small",
  },
  {
    id: "portrait-7",
    src: "/photos/portretni/Portretni foceni ve meste.Liberec.1.jpg",
    alt: "Portrétní focení ve městě, Liberec",
    title: "Portrét ve městě – Liberec",
    category: "portrait",
    size: "large",
  },
  {
    id: "portrait-8",
    src: "/photos/portretni/Portretni foceni ve meste.Liberec.2.jpg",
    alt: "Portrétní focení ve městě, Liberec",
    title: "Portrét ve městě – Liberec 2",
    category: "portrait",
    size: "medium",
  },
  {
    id: "portrait-9",
    src: "/photos/portretni/Portretni foceni ve meste.Liberec.jpg",
    alt: "Portrétní focení ve městě, Liberec",
    title: "Portrét ve městě – Liberec 3",
    category: "portrait",
    size: "small",
  },
  {
    id: "portrait-10",
    src: "/photos/portretni/Portretni foceni. Branzez.jpg",
    alt: "Portrétní focení Bránžež",
    title: "Portrét – Bránžež",
    category: "portrait",
    size: "large",
  },
  {
    id: "portrait-11",
    src: "/photos/portretni/Portretni foceni.atelier.1.jpg",
    alt: "Portrétní focení v ateliéru",
    title: "Portrét – Ateliér",
    category: "portrait",
    size: "medium",
  },
  {
    id: "portrait-12",
    src: "/photos/portretni/Portretni foceni.Liberec.jpg",
    alt: "Portrétní focení Liberec",
    title: "Portrét – Liberec 4",
    category: "portrait",
    size: "small",
  },
  {
    id: "portrait-13",
    src: "/photos/portretni/Portretni foceni.Pod Zebinem.Ceky raj.jpg.jpg",
    alt: "Portrétní focení pod Zebínem, Český ráj",
    title: "Portrét – Pod Zebínem",
    category: "portrait",
    size: "large",
  },
  {
    id: "portrait-14",
    src: "/photos/portretni/Portretni foceni.Trosky.Turnov.jpg.jpg",
    alt: "Portrétní focení Trosky, Turnov",
    title: "Portrét – Trosky",
    category: "portrait",
    size: "medium",
  },

  // REPORTAZNI
  {
    id: "reportage-1",
    src: "/photos/reportazni/Reportazni foceni.U vas doma. Mladejov v Cechach.jpg",
    alt: "Reportážní focení u vás doma, Mladějov v Čechách",
    title: "Reportáž – U vás doma",
    category: "reportage",
    size: "large",
  },
  {
    id: "reportage-2",
    src: "/photos/reportazni/Reportazni fotografie.2.jpg",
    alt: "Reportážní fotografie",
    title: "Reportáž",
    category: "reportage",
    size: "medium",
  },
  {
    id: "reportage-3",
    src: "/photos/reportazni/Rodinna reportaz. Michaela Cizkova.jpg",
    alt: "Rodinná reportáž",
    title: "Rodinná reportáž",
    category: "reportage",
    size: "small",
  },

  // RODINNE
  {
    id: "family-1",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. 2. Michaela Cizkova.jpg",
    alt: "Rodinné focení Český ráj",
    title: "Rodina – Český ráj",
    category: "family",
    size: "large",
  },
  {
    id: "family-2",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. 3. Michaela Cizkova.jpg.jpg",
    alt: "Rodinné focení Český ráj",
    title: "Rodina – Český ráj 2",
    category: "family",
    size: "medium",
  },
  {
    id: "family-3",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. 5. Michaela Cizkova.jpg.jpg",
    alt: "Rodinné focení Český ráj",
    title: "Rodina – Český ráj 3",
    category: "family",
    size: "small",
  },
  {
    id: "family-4",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Michaela Cizkova.jpg",
    alt: "Rodinné focení Český ráj",
    title: "Rodina – Český ráj 4",
    category: "family",
    size: "large",
  },
  {
    id: "family-5",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Mladejov 2. Michaela Cizkova.jpg.jpg",
    alt: "Rodinné focení Český ráj, Mladějov",
    title: "Rodina – Mladějov",
    category: "family",
    size: "medium",
  },
  {
    id: "family-6",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Mladejov. Michaela Cizkova.jpg.jpg",
    alt: "Rodinné focení Český ráj, Mladějov",
    title: "Rodina – Mladějov 2",
    category: "family",
    size: "small",
  },
  {
    id: "family-7",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Rybnik Vezak. Michaela Cizkova.1.jpg",
    alt: "Rodinné focení Český ráj, Rybník Věžák",
    title: "Rodina – Rybník Věžák",
    category: "family",
    size: "large",
  },
  {
    id: "family-8",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Rybnik Vezak. Michaela Cizkova.2.jpg",
    alt: "Rodinné focení Český ráj, Rybník Věžák",
    title: "Rodina – Rybník Věžák 2",
    category: "family",
    size: "medium",
  },
  {
    id: "family-9",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Rybnik Vezak. Michaela Cizkova.jpg",
    alt: "Rodinné focení Český ráj, Rybník Věžák",
    title: "Rodina – Rybník Věžák 3",
    category: "family",
    size: "small",
  },
  {
    id: "family-10",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Sobotka. 1 .Michaela Cizkova.jpg.jpg",
    alt: "Rodinné focení Český ráj, Sobotka",
    title: "Rodina – Sobotka",
    category: "family",
    size: "large",
  },
  {
    id: "family-11",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Sobotka. Michaela Cizkova.jpg.jpg",
    alt: "Rodinné focení Český ráj, Sobotka",
    title: "Rodina – Sobotka 2",
    category: "family",
    size: "medium",
  },
  {
    id: "family-12",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Zebin. Michaela Cizkova 1.jpg",
    alt: "Rodinné focení Český ráj, Zebín",
    title: "Rodina – Zebín",
    category: "family",
    size: "small",
  },
  {
    id: "family-13",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Zebin. Michaela Cizkova 2. jpg.jpg",
    alt: "Rodinné focení Český ráj, Zebín",
    title: "Rodina – Zebín 2",
    category: "family",
    size: "large",
  },
  {
    id: "family-14",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Zebin. Michaela Cizkova 3.jpg",
    alt: "Rodinné focení Český ráj, Zebín",
    title: "Rodina – Zebín 3",
    category: "family",
    size: "medium",
  },
  {
    id: "family-15",
    src: "/photos/rodinne/Rodinne foceni Cesky raj. Zebin. Michaela Cizkova.jpg",
    alt: "Rodinné focení Český ráj, Zebín",
    title: "Rodina – Zebín 4",
    category: "family",
    size: "small",
  },
  {
    id: "family-16",
    src: "/photos/rodinne/Rodinne foceni.Newborn. Turnov. jpg.jpg",
    alt: "Rodinné focení s novorozencem, Turnov",
    title: "Rodina s novorozencem – Turnov",
    category: "family",
    size: "large",
  },

  // ROMANTICKE
  {
    id: "romantic-1",
    src: "/photos/romanticke/Romanticke foceni Cesky raj. Jicin. Michaela Cizkova.jpg.jpg",
    alt: "Romantické focení Český ráj, Jičín",
    title: "Romantické – Jičín",
    category: "romantic",
    size: "large",
  },

  // SVATEBNI
  {
    id: "wedding-1",
    src: "/photos/svatebni/Svatebni foceni.Cesky raj.1.jpg",
    alt: "Svatební focení Český ráj",
    title: "Svatba – Český ráj",
    category: "wedding",
    size: "large",
  },
  {
    id: "wedding-2",
    src: "/photos/svatebni/Svatebni foceni.Cesky raj.2.jpg",
    alt: "Svatební focení Český ráj",
    title: "Svatba – Český ráj 2",
    category: "wedding",
    size: "medium",
  },
  {
    id: "wedding-3",
    src: "/photos/svatebni/Svatebni foceni.Cesky raj.3.jpg",
    alt: "Svatební focení Český ráj",
    title: "Svatba – Český ráj 3",
    category: "wedding",
    size: "small",
  },
  {
    id: "wedding-4",
    src: "/photos/svatebni/Svatebni foceni.Cesky raj.4.jpg",
    alt: "Svatební focení Český ráj",
    title: "Svatba – Český ráj 4",
    category: "wedding",
    size: "large",
  },
  {
    id: "wedding-5",
    src: "/photos/svatebni/Svatebni foceni.Cesky raj.5.jpg",
    alt: "Svatební focení Český ráj",
    title: "Svatba – Český ráj 5",
    category: "wedding",
    size: "medium",
  },
  {
    id: "wedding-6",
    src: "/photos/svatebni/Svatebni foceni.Cesky raj.6.jpg",
    alt: "Svatební focení Český ráj",
    title: "Svatba – Český ráj 6",
    category: "wedding",
    size: "small",
  },
  {
    id: "wedding-7",
    src: "/photos/svatebni/Svatebni foceni.Jicin. Cesky raj.1.jpg",
    alt: "Svatební focení Jičín, Český ráj",
    title: "Svatba – Jičín",
    category: "wedding",
    size: "large",
  },
  {
    id: "wedding-8",
    src: "/photos/svatebni/Svatebni foceni.Jicin. Cesky raj.jpg",
    alt: "Svatební focení Jičín, Český ráj",
    title: "Svatba – Jičín 2",
    category: "wedding",
    size: "medium",
  },

  // TEHOTENSKE
  {
    id: "maternity-1",
    src: "/photos/tehotenske/Tehotenske foceni Cesky raj. Branzez. Michaela Cizkova.jpg.jpg",
    alt: "Těhotenské focení Český ráj, Bránžež",
    title: "Těhotenství – Bránžež",
    category: "maternity",
    size: "large",
  },
  {
    id: "maternity-2",
    src: "/photos/tehotenske/Tehotenske foceni Cesky raj. Branzez.1. Michaela Cizkova.jpg.jpg",
    alt: "Těhotenské focení Český ráj, Bránžež",
    title: "Těhotenství – Bránžež 2",
    category: "maternity",
    size: "medium",
  },
  {
    id: "maternity-3",
    src: "/photos/tehotenske/Tehotenske foceni Cesky raj. Branzez.3. Michaela Cizkova.jpg.jpg",
    alt: "Těhotenské focení Český ráj, Bránžež",
    title: "Těhotenství – Bránžež 3",
    category: "maternity",
    size: "small",
  },
  {
    id: "maternity-4",
    src: "/photos/tehotenske/Tehotenske foceni.Trosky. Jicin. jpg.jpg",
    alt: "Těhotenské focení Trosky, Jičín",
    title: "Těhotenství – Trosky",
    category: "maternity",
    size: "large",
  },
  {
    id: "maternity-5",
    src: "/photos/tehotenske/Tehotenske foceni.Trosky.1.jpg",
    alt: "Těhotenské focení Trosky",
    title: "Těhotenství – Trosky 2",
    category: "maternity",
    size: "medium",
  },
  {
    id: "maternity-6",
    src: "/photos/tehotenske/Tehotenske foceni.Trosky.jpg",
    alt: "Těhotenské focení Trosky",
    title: "Těhotenství – Trosky 3",
    category: "maternity",
    size: "small",
  },
];
